name: svip
main: vip\Main
api: 1.13.1
version: 1.0.0
author: Apple3910
website: EasyPe.pl

commands:
  sponsor:
    Uzyj: /sponsor
    description: "Komenda na zakup sponsora"
    permission: vip.command
permissions:
  vip.command:
    default: true
    description: "Premisje do uzywania komend"
