name: vip
main: vip\Main
api: 2.0.0
version: 1.0.0
author: Apple3910
website: EasyPe.pl

commands:
  vip:
    usage: /vip
    description: "Komenda na zakup vipa"
    permission: vip.command
permissions:
  vip.command:
    default: true
    description: "Premisje do uzywania komend"
